package com.objectcapture

import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.annotations.ReactModule

/**
 * `NativePhotogrammetrySessionSpec` is generated by codegen from
 * `src/specs/NativePhotogrammetrySession.ts`. Photogrammetry is iOS-only, so
 * every method rejects on Android.
 */
@ReactModule(name = NativePhotogrammetrySessionSpec.NAME)
class PhotogrammetrySessionModule(reactContext: ReactApplicationContext) :
    NativePhotogrammetrySessionSpec(reactContext) {

    override fun startReconstruction(
        imagesDirectory: String,
        checkpointDirectory: String,
        outputPath: String,
        detail: String,
        promise: Promise
    ) {
        promise.reject("NOT_IMPLEMENTED", "Photogrammetry is not implemented on Android")
    }

    override fun cancelReconstruction(promise: Promise) {
        promise.reject("NOT_IMPLEMENTED", "Photogrammetry is not implemented on Android")
    }

    override fun listDirectoryContents(directory: String, promise: Promise) {
        promise.reject("NOT_IMPLEMENTED", "Photogrammetry is not implemented on Android")
    }
}
